# permissions for end users to edit customconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customconfig-editor-role
rules:
- apiGroups:
  - cache.mtcil.com
  resources:
  - customconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.mtcil.com
  resources:
  - customconfigs/status
  verbs:
  - get
