
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.mtcil.com
  resources:
  - customconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.mtcil.com
  resources:
  - customconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - cache.mtcil.com
  resources:
  - customconfigs/status
  verbs:
  - get
  - patch
  - update
